import type { OntologyConfig, OntologyEntityConfig, OntologyRelationConfig } from '../types/ontology.js'

export const TYPEGRAPH_B2B_SAAS_ONTOLOGY_VERSION = 'typegraph-b2b-saas-2026-05-13-v2'

const entities: Record<string, OntologyEntityConfig> = {
  company: {
    extends: 'organization',
    description: 'A vendor, customer, prospect, partner, competitor, or other legal business organization.',
  },
  account: {
    extends: 'organization',
    description: 'A customer or prospect business relationship in a CRM. One company can map to multiple accounts across systems or business units.',
  },
  competitor: {
    extends: 'company',
    description: 'A company being compared against the vendor or customer.',
  },
  partner: {
    extends: 'company',
    description: 'A partner organization such as a channel, reseller, SI, OEM, marketplace, or technology partner.',
  },
  person: {
    description: 'A named individual identified by full name plus a disambiguator such as email, company affiliation, role title, or phone.',
  },
  persona: {
    extends: 'role',
    description: 'A buyer, stakeholder, evaluator, user role, team role, or audience segment. Use person for named individuals.',
  },
  team: {
    extends: 'organization',
    description: 'A named internal or customer team or department. Generic terms like "the team" are not entities.',
  },
  product: { description: 'A software product, platform, module, add-on, service, or SKU.' },
  feature: { description: 'A product capability, workflow, setting, module, or functional area.' },
  integration: { description: 'A third-party integration, connector, API, marketplace app, webhook, or data source.' },
  roadmap_item: { extends: 'project', description: 'A planned or in-progress product capability with target timing, owner, and status.' },
  release: { extends: 'event', description: 'A specific product release or version with a version number, date, and scope.' },
  deployment_model: { extends: 'concept', description: 'A hosting, deployment, tenancy, or architecture model such as multi-tenant SaaS, single-tenant, BYOC, on-prem, or hybrid.' },
  data_region: { extends: 'location', description: 'A country, region, data residency location, market, or processing geography.' },
  security_control: { extends: 'technology', description: 'A security, privacy, governance, trust, or access-control mechanism.' },
  compliance_framework: { extends: 'law_regulation', description: 'A compliance standard, regulation, certification, audit framework, or trust program such as SOC 2, ISO 27001, HIPAA, or GDPR.' },
  audit_finding: { extends: 'issue', description: 'A specific finding, observation, exception, or non-conformity from an audit or assessment.' },
  vulnerability_disclosure: { extends: 'issue', description: 'A disclosed security vulnerability, CVE, or coordinated disclosure with severity and remediation status.' },
  opportunity: { extends: 'project', description: 'A specific potential or in-flight deal with stage, amount, close date, owner, and primary account.' },
  deal_stage: { extends: 'concept', description: 'A named pipeline stage such as Prospecting, Discovery, Demo, Evaluation, Negotiation, Closed-Won, or Closed-Lost. Extract only when explicitly named.' },
  lifecycle_stage: { extends: 'concept', description: 'An account or contact lifecycle stage such as Subscriber, Lead, MQL, SQL, Opportunity, Customer, or Evangelist.' },
  poc: { extends: 'project', description: 'A proof-of-concept engagement with scope, criteria, timeline, and outcome.' },
  pilot: { extends: 'project', description: 'A paid or unpaid pilot deployment with limited scope and explicit success criteria.' },
  demo: { extends: 'meeting', description: 'A product demonstration session, often captured as a meeting with an associated recording.' },
  evaluation: { extends: 'project', description: 'A formal product evaluation or trial period with criteria and a decision date.' },
  security_review: { extends: 'project', description: 'A buyer-side security or vendor review with reviewers, scope, and status.' },
  pricing_plan: { extends: 'concept', description: 'A price, package, tier, plan, contract model, discount, or commercial term.' },
  contract: { description: 'An executed agreement document such as an MSA, Order Form, SOW, DPA, NDA, amendment, or renewal order.' },
  renewal: { extends: 'event', description: 'A specific renewal event with renewal date, prior ARR, new ARR, and outcome.' },
  arr: { extends: 'metric', description: 'An Annual Recurring Revenue value at a point in time attached to an account, opportunity, renewal, or contract.' },
  ticket: { description: 'A support, incident, bug, feature, or service-request record with id, status, priority, requester, assignee, and timestamps.' },
  feature_request: { extends: 'issue', description: 'A specific customer-originated request for new or modified product capability.' },
  escalation: { extends: 'issue', description: 'A formal raising of a ticket or account to higher-priority handling with trigger, severity, owner, and status.' },
  health_score: { extends: 'metric', description: 'A point-in-time customer health value with score, color, components, and timestamp.' },
  nps_response: { extends: 'metric', description: 'A single NPS survey response with score, comment, respondent, and timestamp.' },
  csat_response: { extends: 'metric', description: 'A single CSAT or satisfaction survey response with score, comment, respondent, and timestamp.' },
  qbr: { extends: 'meeting', description: 'A Quarterly Business Review session with agenda, outcomes, action items, and attendees.' },
  success_plan: { extends: 'project', description: 'A structured customer success plan with objectives, milestones, and owners.' },
  milestone: { extends: 'event', description: 'A defined customer milestone or success criterion such as first value, production go-live, or users onboarded.' },
  meeting: { description: 'A scheduled interaction such as a call, demo, QBR, workshop, kickoff, or review with host, attendees, time, duration, and source id.' },
  message: { extends: 'document', description: 'A single communication unit such as an email, Slack message, ticket comment, transcript utterance, or note.' },
  signal: { extends: 'concept', description: 'An interpreted observation indicating buyer or customer state. Use evidence, polarity, confidence, and source when available.' },
  requirement: { extends: 'concept', description: 'A buyer, security, procurement, technical, compliance, or questionnaire requirement.' },
  questionnaire: { extends: 'document', description: 'A security questionnaire, RFP, RFI, DDQ, procurement form, or assessment document.' },
  proposal: { extends: 'document', description: 'A generated or uploaded proposal, response, answer-library item, sales document, or procurement response.' },
  use_case: { extends: 'concept', description: 'A business objective, workflow, pain point, operating scenario, or desired outcome.' },
  risk: { extends: 'concept', description: 'A procurement, security, operational, legal, commercial, renewal, or adoption risk.' },
  objection: { extends: 'concept', description: 'A buyer concern, blocker, competitive objection, or sales challenge.' },
  support_policy: { extends: 'document', description: 'A support model, escalation path, SLA practice, customer success process, runbook, or policy.' },
  sla: { extends: 'contract', description: 'A service-level commitment, uptime target, response time, reliability guarantee, or support entitlement.' },
  campaign: { extends: 'project', description: 'A marketing campaign or program with channel, audience, offer, and timeframe.' },
  content_asset: { extends: 'document', description: 'A content item such as a case study, whitepaper, KB article, runbook, FAQ, training material, blog post, or video.' },
  industry: { extends: 'concept', description: 'An industry classification such as Financial Services, Healthcare, Manufacturing, Retail, or Education.' },
  vertical: { extends: 'concept', description: 'A vertical or sub-industry segment such as Insurance, Biotech, or Auto Manufacturing.' },
  geography: { extends: 'location', description: 'A market geography such as a country, region, AMER, EMEA, APAC, or data market.' },
}

const relation = (
  description: string,
  from: string[],
  to: string[],
  extras: Omit<OntologyRelationConfig, 'description' | 'from' | 'to'> = {},
): OntologyRelationConfig => ({ description, from, to, ...extras })

const relations: Record<string, OntologyRelationConfig> = {
  offers: relation('A company offers a product, feature, pricing plan, or support policy.', ['company'], ['product', 'feature', 'pricing_plan', 'support_policy']),
  supports: relation('A product or feature supports a use case, requirement, integration, or deployment model.', ['product', 'feature'], ['use_case', 'requirement', 'integration', 'deployment_model']),
  integrates_with: relation('A product, feature, or integration integrates with another integration or product.', ['product', 'feature', 'integration'], ['integration', 'product'], { symmetric: true }),
  complies_with: relation('An entity explicitly complies with, is certified for, or satisfies a compliance framework or requirement.', ['company', 'product', 'security_control'], ['compliance_framework', 'requirement']),
  requires: relation('A requirement, questionnaire, or use case requires a capability, control, integration, or deployment model.', ['requirement', 'questionnaire', 'use_case'], ['feature', 'security_control', 'integration', 'deployment_model']),
  answers: relation('A proposal, content asset, feature, control, support policy, or message directly answers a requirement, questionnaire, or objection.', ['proposal', 'content_asset', 'feature', 'security_control', 'support_policy', 'message'], ['requirement', 'questionnaire', 'objection']),
  differentiates_from: relation('A company, product, or feature is differentiated from a competitor, product, or feature.', ['company', 'product', 'feature'], ['competitor', 'product', 'feature']),
  targets: relation('A company, product, or feature targets a persona, use case, company, industry, or vertical.', ['company', 'product', 'feature'], ['persona', 'use_case', 'company', 'industry', 'vertical']),
  blocks: relation('A risk, objection, requirement, ticket, or escalation blocks a use case, proposal, deployment model, opportunity, or renewal.', ['risk', 'objection', 'requirement', 'ticket', 'escalation'], ['use_case', 'proposal', 'deployment_model', 'opportunity', 'renewal']),
  mitigates: relation('A feature, security control, or support policy mitigates a risk, objection, or requirement.', ['feature', 'security_control', 'support_policy'], ['risk', 'objection', 'requirement']),
  priced_as: relation('A product or feature is packaged or priced as a pricing plan.', ['product', 'feature'], ['pricing_plan']),
  available_in: relation('A product, feature, or deployment model is available in a data region or pricing plan.', ['product', 'feature', 'deployment_model'], ['data_region', 'pricing_plan']),
  owned_by: relation('A feature, requirement, proposal, ticket, opportunity, or account is owned by a company, person, or team.', ['feature', 'requirement', 'proposal', 'ticket', 'opportunity', 'account'], ['company', 'person', 'team'], { aliases: ['OWNER_IS'] }),
  mentioned_in: relation('An entity is materially mentioned in a questionnaire, proposal, meeting, message, or ticket.', ['company', 'product', 'feature', 'requirement', 'security_control', 'person', 'competitor'], ['questionnaire', 'proposal', 'meeting', 'message', 'ticket']),
  replaces: relation('A product, feature, or release replaces or supersedes another product, feature, competitor, or release.', ['product', 'feature', 'release'], ['product', 'feature', 'competitor', 'release']),
  depends_on: relation('A feature, requirement, deployment model, or release depends on a feature, integration, security control, or release.', ['feature', 'requirement', 'deployment_model', 'release'], ['feature', 'integration', 'security_control', 'release']),
  works_at: relation('A named person works at or is affiliated with a company or account.', ['person'], ['company', 'account'], { aliases: ['WORKS_FOR', 'EMPLOYED_BY'] }),
  reports_to: relation('A person reports to another person.', ['person'], ['person']),
  champions: relation('A person champions an opportunity, account, or product.', ['person'], ['opportunity', 'account', 'product']),
  economic_buyer_for: relation('A person is the economic buyer for an opportunity.', ['person'], ['opportunity']),
  evaluates: relation('A person evaluates a product or opportunity.', ['person'], ['product', 'opportunity']),
  sponsors: relation('A person sponsors an opportunity or account.', ['person'], ['opportunity', 'account']),
  end_user_of: relation('A person is an end user of a product or feature.', ['person'], ['product', 'feature']),
  parent_of: relation('A company or account is the parent of another company or account.', ['company', 'account'], ['company', 'account']),
  subsidiary_of: relation('A company or account is a subsidiary of another company or account.', ['company', 'account'], ['company', 'account']),
  attended: relation('A person attended a meeting.', ['person'], ['meeting']),
  hosted: relation('A person hosted a meeting.', ['person'], ['meeting']),
  authored: relation('A person authored a message, proposal, or content asset.', ['person'], ['message', 'proposal', 'content_asset']),
  discussed_in: relation('An entity was materially discussed in a meeting or message.', ['company', 'product', 'feature', 'requirement', 'opportunity', 'risk', 'objection', 'use_case', 'competitor'], ['meeting', 'message']),
  attached_to: relation('A contract, content asset, proposal, or questionnaire is attached to an opportunity, account, or renewal.', ['contract', 'content_asset', 'proposal', 'questionnaire'], ['opportunity', 'account', 'renewal']),
  advances: relation('A signal, meeting, or message advances an opportunity.', ['signal', 'meeting', 'message'], ['opportunity']),
  qualifies: relation('A signal or requirement qualifies an opportunity.', ['signal', 'requirement'], ['opportunity']),
  disqualifies: relation('A signal, objection, or risk disqualifies an opportunity.', ['signal', 'objection', 'risk'], ['opportunity']),
  influences: relation('A person, content asset, or campaign influences an opportunity.', ['person', 'content_asset', 'campaign'], ['opportunity']),
  chose_over: relation('An account chose the vendor or product over a competitor.', ['account'], ['competitor']),
  lost_to: relation('An opportunity was lost to a competitor.', ['opportunity'], ['competitor']),
  won_against: relation('An opportunity was won against a competitor.', ['opportunity'], ['competitor']),
  considered_alongside: relation('A competitor was considered alongside an opportunity.', ['competitor'], ['opportunity']),
  drives_expansion: relation('A signal, use case, or feature request drives expansion for an opportunity or account.', ['signal', 'use_case', 'feature_request'], ['opportunity', 'account']),
  blocks_renewal: relation('A ticket, escalation, risk, or objection blocks a renewal or opportunity.', ['ticket', 'escalation', 'risk', 'objection'], ['renewal', 'opportunity']),
  raised_by: relation('A ticket, feature request, or objection was raised by a person or account.', ['ticket', 'feature_request', 'objection'], ['person', 'account']),
  assigned_to: relation('A ticket, escalation, success plan, or milestone is assigned to a person or team.', ['ticket', 'escalation', 'success_plan', 'milestone'], ['person', 'team']),
  escalated_to: relation('A ticket or escalation was escalated to a person or team.', ['ticket', 'escalation'], ['person', 'team']),
  resolved_by: relation('A ticket or escalation was resolved by a person, release, or feature.', ['ticket', 'escalation'], ['person', 'release', 'feature']),
  workaround_for: relation('A ticket or content asset provides a workaround for another ticket.', ['ticket', 'content_asset'], ['ticket']),
  caused_by: relation('A ticket, escalation, or risk was caused by a release, integration, feature, or ticket.', ['ticket', 'escalation', 'risk'], ['release', 'integration', 'feature', 'ticket']),
  references: relation('A message, ticket, or meeting references a content asset, feature, or product.', ['message', 'ticket', 'meeting'], ['content_asset', 'feature', 'product']),
  priced_at: relation('A contract, renewal, or opportunity is priced at an ARR value or pricing plan.', ['contract', 'renewal', 'opportunity'], ['arr', 'pricing_plan']),
  party_to: relation('A company or person is party to a contract.', ['company', 'person'], ['contract']),
  renewed_on: relation('A contract renewed through a specific renewal event.', ['contract'], ['renewal']),
  transitioned_to: relation('An account, opportunity, ticket, or person transitioned to a deal or lifecycle stage.', ['account', 'opportunity', 'ticket', 'person'], ['deal_stage', 'lifecycle_stage']),
  churned_on: relation('An account churned on a renewal event.', ['account'], ['renewal']),
  expresses_sentiment_about: relation('A person or account expresses sentiment about a product, feature, company, competitor, or support policy.', ['person', 'account'], ['product', 'feature', 'company', 'competitor', 'support_policy']),
  indicates_health_of: relation('A signal, health score, NPS response, or CSAT response indicates account health.', ['signal', 'health_score', 'nps_response', 'csat_response'], ['account']),
  signals_churn_for: relation('A signal, ticket, or escalation signals churn risk for an account or renewal.', ['signal', 'ticket', 'escalation'], ['account', 'renewal']),
  sourced_from: relation('An opportunity, account, or person was sourced from a campaign, content asset, or partner.', ['opportunity', 'account', 'person'], ['campaign', 'content_asset', 'partner']),
  engaged_with: relation('A person or account engaged with a campaign, content asset, or meeting.', ['person', 'account'], ['campaign', 'content_asset', 'meeting']),
  documented_by: relation('A feature, product, security control, use case, or integration is documented by a content asset.', ['feature', 'product', 'security_control', 'use_case', 'integration'], ['content_asset']),
}

export const TYPEGRAPH_B2B_SAAS_ONTOLOGY: OntologyConfig = {
  version: TYPEGRAPH_B2B_SAAS_ONTOLOGY_VERSION,
  profiles: ['saas'],
  entities,
  relations,
  resolution: {
    genericAliasBlocklist: [
      'platform', 'product', 'solution', 'feature', 'customer', 'vendor', 'company',
      'system', 'service', 'team', 'org', 'organization', 'group', 'department',
      'business', 'enterprise', 'firm', 'agency', 'meeting', 'call', 'demo',
      'sync', 'standup', 'session', 'event', 'review', 'issue', 'problem', 'bug',
      'ticket', 'request', 'thing', 'item', 'task', 'incident', 'deal', 'account',
      'opportunity', 'contract', 'agreement', 'plan', 'pricing', 'tool', 'app',
      'application', 'software', 'integration', 'api', 'they', 'we', 'us', 'our',
      'their', 'them', 'someone', 'somebody', 'anyone', 'everyone', 'the customer',
      'the client', 'the user', 'the buyer', 'the prospect', 'the rep', 'the team',
      'the company', 'the org', 'the account', 'the vendor', 'the partner',
      'the cto', 'the ceo', 'the cfo', 'the cio', 'the ciso', 'the vp',
      'the manager', 'the lead', 'the admin', 'the engineer', 'the architect',
      'the director', 'the champion', 'the decision maker', 'the evaluator',
      'the sponsor', 'today', 'tomorrow', 'yesterday', 'next week', 'last week',
      'next quarter', 'last quarter', 'this month', 'last month', 'eoq', 'eoy',
    ],
    coordinateEntityTypes: [
      'company', 'product', 'feature', 'integration', 'compliance_framework',
      'person', 'account', 'persona', 'team', 'use_case', 'feature_request',
      'industry', 'vertical', 'geography', 'deal_stage', 'lifecycle_stage',
      'roadmap_item', 'content_asset', 'partner', 'campaign', 'security_control',
      'risk', 'objection',
    ],
  },
  prompt: {
    entityGuidelines: [
      'Prefer specific named products, companies, accounts, features, integrations, controls, regions, buyer roles, requirements, risks, objections, and commercial objects over generic nouns.',
      'Never extract pronouns or generic role references such as "they", "the customer", or "their CTO" as entities. Wait for a named person, named account, named team, or named role/persona.',
      'Use person for named individuals only. Champion, Economic Buyer, Evaluator, and Sponsor are relations to opportunities or accounts, not entity subtypes.',
      'Distinguish company as the legal organization from account as the CRM/customer relationship. If the text is about a customer relationship, default to account.',
      'Distinguish competitor from partner by the relationship in context. The same company can be both across different facts.',
      'Extract tickets, incidents, and feature requests only when there is an identifier, status, or clearly bounded scope. Generic complaints become signal, risk, or objection entities.',
      'Extract signal only when there is explicit evidence for customer or buyer state, and preserve polarity, confidence, evidence quote, and source when available.',
      'Attach commercial numbers such as ARR, contract value, and pricing to account, opportunity, contract, renewal, arr, or pricing_plan. Do not create free-floating numeric entities.',
      'Do not reify sales methodologies such as MEDDPICC, BANT, or SPICED as entities. Store their field values as relations or attributes when explicit.',
    ],
    relationGuidelines: [
      'Both endpoints of a relation must be named or explicitly bounded entities. If an endpoint is only a pronoun or generic noun, skip the relation.',
      'Relations affecting deal outcome, churn, security, or customer health require explicit evidence in the text. Do not infer them from tone or temporal proximity alone.',
      'Competitive relations such as chose_over, lost_to, considered_alongside, and won_against require an explicitly named competitor.',
      'Causal relations such as caused_by require an explicit causal connector or a same-incident statement. Do not infer causation from co-occurrence alone.',
      'For call transcripts and messages, attribute claims to the speaker or author when the source makes that available.',
      'Avoid hypothetical or conditional statements as facts. "Might churn" is a low-confidence signal at most, not a churn event.',
      'Prefer structured CRM, ticket, and billing fields over LLM inference when structured values are present.',
    ],
  },
  metadata: {
    owner: 'typegraph',
    curated: true,
    domain: 'b2b-saas',
    notes: 'Curated B2B SaaS ontology for mixed CRM, sales, support, success, security, product, and transcript extraction. Advanced policy constraints are intentionally left to TypeGraph policies rather than encoded as unsupported ontology fields.',
  },
}
